= Cheatsheet NVS 5AHIF 2021

== Wichtige Links


* link:https://quarkus.io/guides/hibernate-orm-panache[hibernate-orm-panache]
* link:https://quarkus.io/guides/websockets[websockets]
* link:https://quarkus.io/guides/security[security]
* link:https://edufs.edu.htl-leonding.ac.at/~t.stuetz/download/nvs/scripts/[scripts]
* link:https://stackoverflow.com/questions/65387621/how-to-post-form-based-authentication[form-based-authentication]
* link:https://quarkus.io/guides/getting-started-testing[quarkus tests]
* link:https://quarkus.io/guides/security-properties[security-properties]
* link:https://davidenkovic.github.io/school-notes/jpa-test.html[JPA]
* link:http://fxapps.blogspot.com/2019/12/quarkus-application-with-form.html[quarkus-application-with-form]
* link:https://quarkus.io/guides/security-built-in-authentication[security-built-in-authentication]
* link:https://stackoverflow.com/a/43045241[read JSON]

== Entity

* @Entity
* @Table(name = "table_name")
* @Id
** sollte Long sein
* @GeneratedValue(strategy = GenerationType.IDENTITY)
* @JoinColumn(name = "ROOM_NO")
** Für Foreign-Key-Spalte in der Tabelle der referenzierenden Entität
* @Column(name = "DATE_TO", cascade = {CascadeType.All})


=== String.format

[source,java]
----
@Override
public String toString() {
return String.format(...);
}
----

String -> %s +
Decimal integer -> %d +
Date -> %tF

=== Unique Constraints

[source,java]
----
@Table(name = "H_CUSTOMER",uniqueConstraints = @UniqueConstraint(columnNames={"FIRST_NAME", "LAST_NAME"}))
----

== Control

=== ORM (Panache)

Ohne dem kein Panache.
*@ApplicationScoped* nicht vergessen!

[source,java]
----
@ApplicationScoped
public class Repository implements Repository<Entity>{
    ...
}
----


=== Insert Data

[source,java]
----
@Transactional
@PostConstruct
public void insertData(){
    ...
}
----

*@Transactional* immer verwenden bei änderungen in der DB.

=== NamedQuery

[source,java]
----
@NamedQueries({
        @NamedQuery(name = "Person.findByFirstName", query = "select p from Person p where firstName = :firstName ")
})
----

==== getEntityManager

[source,java]
----
return (Customer)getEntityManager()
.createNamedQuery("Customer.findByFirstNameAndLastName") // name der NamedQuery
.setParameter("firstName", firstName) // parameter :firstName
.getSingleResult();

----

=== Panache
[source,java]
----
PanacheQuery<Person> query = Person.find("#Person.findByFirstName", name).firstResult(); //name = parameter
----

==== PanacheQuery

[source, java]
----
PanacheQuery<Person> query = Person.find("status", Status.Alive).project(Person.class);
----





=== Unmodifiable List

[source,java]
----
Collections.unmodifiableList(...)
----

=== Read CSV

[source,java]
----
List<String> readFile(String fileName) {
    URL url = Thread.currentThread().getContextClassLoader().getResource(fileName);
    assert url != null;
    try (Stream<String> stream = Files.lines(Paths.get(url.getPath()), StandardCharsets.UTF_8)) {
        return stream
                .skip(1)
                .distinct()
                .map(line -> {
                    if (line.length() <= 2) {
                        return line + " - 1";
                    } else {
                        return line + " - 2";
                    }
                })
                .collect(Collectors.toList());
    } catch (IOException e) {
        e.printStackTrace();
    }
    return null;
}
----

[source,java]
----
private void readCsv() {
try {
    URL url = Thread.currentThread().getContextClassLoader().getResource(FILE_NAME);
    assert url != null;

    Files.readAllLines(Paths.get(url.getPath()), StandardCharsets.UTF_8)
            .stream()
            .skip(1)
            .distinct()
            .map(line -> parseCourse(line.split(";")))
            .forEach(em::merge);
    } catch (IOException e) {
        e.printStackTrace();
    }
}
----
== Boundary/Service

* @RequestScoped
* @Path("/endpoint")

=== Inject Repository

[source,java]
----
@Inject
Repository repository;
----

=== UriInfo

@Context UriInfo info

[source,java]
----
UriBuilder uriBuilder = info
.getAbsolutePathBuilder()
.path(Long.toString(person.getId()));
return Response.created(uriBuilder.build()).build();
----

[source,java]
----
 return Response.status(400).header("reason", "out of range ").build();

----

=== Params

* @PathParam("name")

``localhost:8080/api/dave``

* @QueryParam("name")


``localhost:8080/api?name=dave``

erweiterung mit *&*

``localhost:8080/api?name=dave&age=18``


== JAX-RS @FormParam example (HTML-Formular)

=== HTML Form

.simple HTML form with “post” method
[source,html]
----
<html>
<body>
<h1>JAX-RS @FormQuery Testing</h1>

    <form action="rest/user/add" method="post">
        <p>
            Name : <input type="text" name="name" />
        </p>
        <p>
            Age : <input type="text" name="age" />
        </p>
        <input type="submit" value="Add User" />
    </form>

</body>
</html>
----

=== @FormParam Example

.Example to use @FormParam to get above HTML form parameter values.
[source,java]
----
import javax.ws.rs.FormParam;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;

@Path("/user")
public class UserService {

    @POST
    @Path("/add")
    public Response addUser(
        @FormParam("name") String name,
        @FormParam("age") int age) {

        return Response.status(200)
            .entity("addUser is called, name : " + name + ", age : " + age)
            .build();

    }

}
----


== Marshalling und Unmarshalling JSON

[source,java]
----
@JsonSerialize(using = LocalDateSerializer.class)
@JsonDeserialize(using = LocalDateDeserializer.class)
@Column(name = "DATE_SIGNED")
private LocalDate contractSigned;

    @JsonSerialize(using = LocalDateSerializer.class)
    @JsonDeserialize(using = LocalDateDeserializer.class)
    @Column(name = "DATE_END")
    private LocalDate contractEnd;
----

[source,java]
----
public class LocalDateDeserializer extends JsonDeserializer<LocalDate> {
DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    @Override
    public LocalDate deserialize(JsonParser arg0, DeserializationContext arg1) throws IOException {
        return LocalDate.parse(arg0.getText(), df);
    }
}
----

[source,java]
----
public class LocalDateSerializer extends JsonSerializer<LocalDate> {
    @Override
    public void serialize(LocalDate arg0, JsonGenerator arg1, SerializerProvider arg2) throws IOException {
        arg1.writeString(arg0.toString());
    }
}
----

=== JSON P

[source,java]
----
JsonObjectBuilder classroomBuilder = Json.createObjectBuilder();

classroomBuilder.add("klasse", "4ahif");
classroomBuilder.add("raum", "107");

JsonObject classroom = classroomBuilder.build();

----



=== Simple post

[source,java]
----
@POST
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public Response addSurvey(Survey survey) {
    Survey survey1 = surveyRepository.save(survey);

    if (survey1 != null)
    {
        return Response.ok(survey1).build();
    }

    return  Response.status(Response.Status.BAD_REQUEST).build();
}
----

=== SequenceGenerator

[source, java]
----
@Id
@SequenceGenerator(
        name = "personSequence",
        sequenceName = "person_id_seq",
        allocationSize = 1, //increment
        initialValue = 4) //start
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "personSequence")
public Integer id;
----

[source,java]
----


@ApplicationScoped
public class PersonRepository implements PanacheRepositoryBase<Person,Integer> {
    //...
}
----

=== Application Properties for Hibernate

[source, properties]
----
# configure your datasource
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = app
quarkus.datasource.password = app
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/db

quarkus.hibernate-orm.database.generation = drop-and-create

----

=== RBAC

.HTTP Request
[source,http request]
----
GET http://localhost:8080/api/admin
Authorization: Basic admin admin
----

.GET
[source, java]
----
@GET
@RolesAllowed({"admin"})
@Produces(MediaType.TEXT_PLAIN)
@Path("/admin")
public String adminResource() {
    return "admin";
}
----

.Properties
[source,properties]
----
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.realm-name=Quarkus
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.admin=admin
quarkus.security.users.embedded.roles.admin=admin
----
